Add datatype property
Semantic-Society/Neologism pull request #172
Opened 2021-05-18 11:30 UTC by husaynali

2021-05-25 06:37 UTC, JohannesLipp requested changes
Please fix the small comments. The rest looks good, thank you!

2021-05-25 06:37 UTC, JohannesLipp commented on app/src/app/mxgraph/mxgraph.component.ts
> +    // this.mx
Please uncomment or remove this code comment, thank you.

2021-05-25 06:37 UTC, JohannesLipp commented on app/src/app/mxgraph/mxgraph.ts
> +        // TODO: Check if multiple listener on same event creating UI flow disturbances
Please create an issue for this new todo, so that we can tackle it later.

2021-05-25 06:37 UTC, JohannesLipp commented on app/src/app/mxgraph/mxgraph.ts
> +        // TODO in principle getCell should work, but upon inserting there is an issue and the cell gets assingned a new id
Please create an issue so that we can tackle this later.

2021-05-25 11:27 UTC, husaynali commented on app/src/app/mxgraph/mxgraph.component.ts
> +    // this.mx
It already has a TODO req on it, so no need to delete it or uncomment for now

2021-05-25 11:28 UTC, husaynali commented on app/src/app/mxgraph/mxgraph.ts
> +        // TODO: Check if multiple listener on same event creating UI flow disturbances
There more than one TODOs, let us do this in our upcoming session.

2021-05-25 11:28 UTC, husaynali commented on app/src/app/mxgraph/mxgraph.ts
> +        // TODO in principle getCell should work, but upon inserting there is an issue and the cell gets assingned a new id
There more than one TODOs, let us do this in our upcoming session.

2021-05-25 11:29 UTC, husaynali commented
For the TODOs I have created a note which we can discuss in our upcoming sessions.

2021-05-25 21:46 UTC, alihussainiam commented
> Please fix the small comments. The rest looks good, thank you!

#172 

removed and added a note for TODO to discuss in our upcoming session

2021-05-26 09:52 UTC, JohannesLipp commented on app/src/app/mxgraph/property-edit-form/property-edit.component.ts
> +  xsdDataTypes = [
@alihussainiam We define this constant list three times - is this "good practice"?

2021-05-26 10:36 UTC, alihussainiam commented on app/src/app/mxgraph/property-edit-form/property-edit.component.ts
> +  xsdDataTypes = [
true it is not a good practice. There is an issue in angular templating or maybe I understood It wrongly. When I try to import the const from a single location and use it in angular templates (not component)) then it becomes empty.

2021-05-26 10:42 UTC, alihussainiam commented on app/src/app/mxgraph/property-edit-form/property-edit.component.ts
> +  xsdDataTypes = [
I have fixed this now using [stackoverflow post](https://stackoverflow.com/questions/40237561/how-to-access-a-constant-in-an-angular-2-component-and-service/40237663)

2021-05-26 13:45 UTC, JohannesLipp requested changes
This looks great, thank you so much! Just one small request in the export:
We accidentally add `<http://www.w3.org/2001/XMLSchema#integer>` instead of the DatatypeProperty (i.e., hasName and hasContact in your example) - please update this. Thank you!

Detailed example:
1. Replace the subject in `<http://www.w3.org/2001/XMLSchema#string> a <http://www.w3.org/2002/07/owl#DatatypeProperty> .` with `[...]#hasContact`
2. The same for `<http://www.w3.org/2001/XMLSchema#integer> <http://www.w3.org/2000/01/rdf-schema#range> <http://www.w3.org/2001/XMLSchema#integer> .`

2021-05-26 16:43 UTC, alihussainiam commented
> This looks great, thank you so much! Just one small request in the export:
> We accidentally add `<http://www.w3.org/2001/XMLSchema#integer>` instead of the DatatypeProperty (i.e., hasName and hasContact in your example) - please update this. Thank you!
> 
> Detailed example:
> 
> 1. Replace the subject in `<http://www.w3.org/2001/XMLSchema#string> a <http://www.w3.org/2002/07/owl#DatatypeProperty> .` with `[...]#hasContact`
> 2. The same for `<http://www.w3.org/2001/XMLSchema#integer> <http://www.w3.org/2000/01/rdf-schema#range> <http://www.w3.org/2001/XMLSchema#integer> .`

Please check the description box I have updated the export sample. Code has been adapted

2021-05-26 19:31 UTC, merged