Add make proxivocab optional
Semantic-Society/Neologism pull request #240
Opened 2022-09-27 11:32 UTC by alihussainiam

closes #224

2022-09-28 09:48 UTC, JohannesLipp requested changes
Good work, thank you! Please just revert the deletions from the gitignore, so we can merge it, thanks!

2022-09-28 09:48 UTC, JohannesLipp commented on .gitignore
> -# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and Webstorm
I suggest to keep these entries in the gitignore for people that use a JetBrain IDE for contributing to this project.

2022-09-28 09:48 UTC, JohannesLipp commented on app/src/app/home-dashboard/vocabulary-list/vocabulary-list.component.ts
> +     * @param vocab_id TODO (Johannes): TBD
Please open an issue so that we do not forget about this, thanks!

2022-10-06 09:10 UTC, alihussainiam commented on .gitignore
> -# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and Webstorm
[a476fe0](https://github.com/Semantic-Society/Neologism/pull/240/commits/a476fe0cb733f12df92b14a8222af24c3388e674) solves this issue. thank you

2022-10-10 07:41 UTC, merged